awe:
  version: 1
  rendering:
    interval: 15
    blocks: 1000
    queue-limit-hard: 500000
    queue-limit-soft: 250000
  checkVersion: true
  logger: none
#  logger: logBlock
#  logger: coreProtect
#  logger: prism