awe:
  version: 1
  rendering:
    interval: 15
    talk-interval: 10
    blocks: 1000
    blocks-vip: 1000    
    queue-max-size: 10000000
    queue-limit-hard: 500000
    queue-limit-soft: 250000
  checkVersion: true  
  defaultOn: true
  physicsFreez: true
  blocksHub:
    logBlocks: true
    checkAccess: false
  enabledOperations:
    - undo
    - redo
    - fillXZ
    - removeAbove
    - removeBelow
    - removeNear
    - setBlocks
    - replaceBlocks
    - makeCuboidFaces
    - makeCuboidWalls
    - overlayCuboidBlocks
    - naturalizeCuboidBlocks
    - stackCuboidRegion
    - moveCuboidRegion
    - drainArea
    - fixLiquid
    - makeCylinder
    - makeSphere
    - makePyramid
    - thaw
    - simulateSnow
    - green
    - makePumpkinPatches
    - makeForest
    - makeShape
    - deformRegion
    - hollowOutRegion
