name: AsyncWorldedit
main: org.PrimeSoft.AsyncWorldedit.PluginMain
version: 0.1
website: http://dev.bukkit.org/server-mods/async_worldedit/
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
depend: [WorldEdit]
softdepend: [CoreProtec, LogBlock, Prism]
commands:
  awe:
    description: 'Displays the help for Async world edit.'
    usage: /<command>
    aliases: /awe
permissions:
