name: AsyncWorldedit
main: org.primesoft.asyncworldedit.PluginMain
version: 1.0RC2
website: http://dev.bukkit.org/server-mods/async_worldedit/
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
depend: [WorldEdit, BlocksHub]
softdepend:
commands:
  awe:
    description: 'Displays the help for Async world edit.'
    usage: /<command>
    aliases: /awe
permissions:
