name: AsyncWorldedit
main: org.primesoft.asyncworldedit.PluginMain
version: 0.4
website: http://dev.bukkit.org/server-mods/async_worldedit/
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
depend: [WorldEdit]
softdepend: [CoreProtect, LogBlock, Prism, HawkEye, PlotMe]
commands:
  awe:
    description: 'Displays the help for Async world edit.'
    usage: /<command>
    aliases: /awe
permissions:
